name: Deploy maven package

on:
  push:
    branches: [ mainline ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Create Maven settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "github", "username": "trjohnny", "password": " ${{ secrets.MAVEN_DEPLOY_TOKEN }}"}]'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_DEPLOY_TOKEN }}
