name: Deploy maven package

on:
  push:
    branches: [ mainline ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Publish package
        run: |
          mvn --batch-mode deploy
          cat ~/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.MAVEN_DEPLOY_TOKEN }}
